export const carList = [
    {
        name : 'The Adventures of Sherlock Holmes',
        image : 'http://www.loyalbooks.com/image/detail/55.jpg',
        music : ['http://www.archive.org/download/adventures_sherlockholmes_1007_librivox/adventuresherlockholmes_01_doyle_64kb.mp3','http://www.archive.org/download/adventures_sherlockholmes_1007_librivox/adventuresherlockholmes_02_doyle_64kb.mp3','http://www.archive.org/download/adventures_sherlockholmes_1007_librivox/adventuresherlockholmes_03_doyle_64kb.mp3'],
        summary :'The Adventures of Sherlock Holmes is the third book in the original Sherlock Holmes series. It shadows the experiences of detective Sherlock Holmes, an enigmatic genius, as he tries to unravel the mystery of each investigation he partakes in. Set in late 19th century London, the novel not only creates a successful mystery plot, but also circulates through real locations including Hyde Park, the river Thames, St George’s Church in Hanover Square, as well as adding fictional places to spice things up. The vibrant reoccurring illustrations of London’s means of transportation are also worth noting.The novel begins in the famous apartment 221B Baker Street, home to Sherlock Holmes who is visited by clients in need of assistance in resolving various issues. Unsurprisingly, Sherlock Holmes works his magic in order to find a logical solution to each mystery. Narrated through the perspective of Dr. Watson, Holmes’s close friend and companion, he serves as a monitor as he accompanies or is given a full account of the sequence of events surrounding investigation details. Watson then documents each adventure and shares it with the readers which in turn act as memoirs of Holmes’s achievements. This type of narration only enhances the sense of mystery surrounding each case because of the occasional missing detail and leaves the reader wondering about the next course of action. Interestingly, Holmes offers logical explanations for each of his solutions, but nevertheless manages to keep the audience on their toes. Family fortune, reputation, social status and moral weakness are just some of the themes Doyle explores in his novel of suspense and mystery. '
    },
    {
        name : 'The Mystery of the Yellow Room',
        image : 'http://www.loyalbooks.com/image/detail/Mystery-of-the-Yellow-Room.jpg',
        music : ['http://www.archive.org/download/mystery_yellow_room_0901_librivox/mysteryoftheyellowroom_01_leroux_64kb.mp3','http://www.archive.org/download/mystery_yellow_room_0901_librivox/mysteryoftheyellowroom_02_leroux_64kb.mp3','http://www.archive.org/download/mystery_yellow_room_0901_librivox/mysteryoftheyellowroom_03_leroux_64kb.mp3'],
        summary :'One of the first locked room mysteries, The Mystery of the Yellow Room focuses on a supposedly impossible crime which has been committed within a locked room. The novel was initially published in the French periodical L’illustration, and was later published as a book in 1908. It is the first of a series of novels featuring the famous fictional reporter Joseph Rouletabille.The mystery begins when Joseph Rouletabille, a reporter and amateur sleuth is sent to investigate a crime scene at the Château du Glandier, home to renowned chemist Joseph Stangerson. In the focus of the crime is none other than professor Stangerson’s daughter Mathilde. She has been viciously attacked and almost killed in her room, or as the title suggests – the yellow room. What makes the crime so bewildering is the fact that it took place in a room locked from the inside with no apparent exit for the perpetrator.As Miss Stangerson is found alone lying on the floor, the assailant seems to have left significant clues behind, including a bloody mutton bone, a bloody handprint on the wall, and some old boots. Accompanied by his friend and lawyer Sainclair, Rouletabille gains access to the crime scene and interrogates some suspicious characters. The official detective assigned to the case is Frederick Larson, who becomes somewhat of a friendly rival to Rouletabille, and suspects Miss Stangerson’s fiancé Robert Darzac to be involved in the crime. As the mystery unfolds, the darkest secrets and twisted nature of the characters are slowly revealed.A novel portraying the many facets of deception, hazardous ambition and foul play, The Mystery of the Yellow Room sets the benchmark for detective fiction. Furthermore, readers are intellectually challenged to follow the many clues left behind, pushing them into the role of detective in hope of unraveling the mystery. Nevertheless, intriguing and nail biting to the very end, Leroux has effectively masterminded a perplexing mystery, widely celebrated to this very day.'
    }
]